name: codesphere
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^3.0.3

  # Responsive Layout
  layout: ^1.0.5

  # Styling & Utilities
  google_fonts: ^6.3.2
  url_launcher: ^6.3.2

  # Animations
  flutter_animate: ^4.5.2
  lottie: ^3.3.2
  animated_text_kit: ^4.3.0

  # Firebase/Persistence
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0

  # Utils
  go_router: ^17.0.0
  flutter_svg: ^2.2.3
  intl: any
  scrollable_positioned_list: ^0.3.8
  font_awesome_flutter: ^10.12.0
  web: ^1.1.1
  visibility_detector: ^0.4.0+2
  firebase_analytics: ^12.0.4
  equatable: ^2.0.7
  logger: ^2.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/